### ISSUE TITLE
Per-application Device Configuration (Advanced display device option)

### ISSUE THREAD

**Issue by ruifung** [ClassicOldSong/Apollo#259]
I've been running the v0.2.8 builds and have a spot of feedback to give.

It would be nice to have this option on a per-application basis to better support this use case:
1. A 'Desktop' application that turns of all but the virtual display.
2. A 'External Display' application that just only attaches a virtual display.

**Comment by ClassicOldSong** [comment]
You can already do this by enabling "Use app identity" and "Always use virtual display" on the specific app.

Set display configuration to "Verify only" or "Activate only" in Audio/Video tab, do not set "Disable other displays", it's chaotic.

The first time you start the app you can use Windows settings to configure display arrangements and it'll be remembered automatically.

**Comment by ruifung** [comment]
That would almost work except that I need different scaling factor depending on the client I'm connecting from.

And windows is terrible at picking the appropriate UI scaling factor automatically. E.g. on my tablet, I prefer it set to 1.5 or 1.75, but on my fold phone, set to 2.0

**Comment by ClassicOldSong** [comment]
You can also configure the desired DPI manually in Windows settings while the client is connected, and it'll remember it automatically.

There's no difference if you're using virtual display. It's for changing/turning on/off physical display. You can even set it to disabled if you're not interested in streaming your physical display.

**Comment by ruifung** [comment]
Yep. Therein lies the problem.

If I set "use app identity" windows remembers the DPI based on the app identity. But I need it based on client.
If I don't, it remembers disabled displays / extend/mirror mode / DPI based on client. But I need at least the first 2 based on application, but the last one based on client.

Guess I'll stick to using MultiMonitorTool in prep commands to compensate for the first 2 then.

**Comment by ruifung** [comment]
Not if it's an option on the application level just like "Use App Identity", maybe "Append App Identity". Then it would only be (client count) * (apps with option enabled) count additional identities. 

Either way, just thought this might be convenient to have, but otherwise just using MMT to wrangle windows works just as well too.

Just letting windows remember DPI, and use MMT to set up the desired monitor configuration on a per-application basis.

**Comment by ClassicOldSong** [comment]
I'll think about whether there's a better UX for this. The upstream change for display configuration is chaotic enough...

**Comment by ClassicOldSong** [comment]
https://github.com/ClassicOldSong/Apollo/releases/tag/v0.2.9-alpha.1

Done.

**Comment by ruifung** [comment]
Thanks! That works exactly as I thought it would.
I can now just flag my "External Monitor" application with this option and windows will handle the rest.

Also, of note, I think you forgot the localization text for it, but cheers.

**Comment by Her0es** [comment]
Does this work as per client resolution rescaler? As in say, I have an iPad that uses a lower resolution when requesting but will change the host to something higher like x1.2? Same thing for say my steam deck. I request 1280x800 but it'll set the host to 2560x1600? But only for those specific clients and do no scaling per other clients?

**Comment by ClassicOldSong** [comment]
Nope, per client scale is only supported in Artemis for now.
