### ISSUE TITLE
Installation triggered a graceful system restart

### ISSUE THREAD

**Issue by lanmaster53** [ClassicOldSong/Apollo#554]
During the install process when the VigEm Bus driver was being installed, the system executed what looked like a graceful reboot. The OS behaved as if I told it to reboot, with the "Restarting" splash screen, etc. The only change I made to the install process was uncheck the box for starting Apollo with the OS, so when the computer finished rebooting, I manually started Apollo. I was immediately notified that VigEm Bus was not present and needed to be installed. I re-ran the Apollo installation a second time, it did NOT restart, and everything is working properly now. I work in the information security field, so anytime something like a this happens, I am immediately suspicious of the software. I spent time Googling and looking all over the VigEm and Apollo Github pages and couldn't find any other reference to this. Any idea what could cause this? Has anyone else reported this issue? Thanks.

**Comment by ClassicOldSong** [comment]
This shouldn't be happening, unless it's rebooted coinsidentally.

Maybe your system has something configured to auto reboot when a new driver is installed? The SudoVDA driver installation may cause the system to ask if you want to reboot but it's not needed.

**Comment by lanmaster53** [comment]
I keep a pretty tidy machine and I've never had a piece of software do this before. It was strange that it never even asked. It just did it right in the middle of the install process.

I did find this, https://github.com/nefarius/ViGEmBus/issues/132. I don't know what version you are using, but I wonder if there were remnants of an existing version of ViGEm on the OS from my Sunshine days, and when it went to install ViGEm, it triggered the uninstall instead, which led to this issue. Could that be it?

**Comment by ClassicOldSong** [comment]
Might be. The inataller downloads the last release of vigembus and installs it automatically if you have the tick checked.

**Comment by lanmaster53** [comment]
That reboot issue was fixed in a later release, so if Apollo is grabbing the newest version, this shouldn't be an issue. Hm...

**Comment by ClassicOldSong** [comment]
I think the reboot might still be triggered by the uninstall process of the old version, so the new installer still can't prevent the reboot from previous versions.

**Comment by lanmaster53** [comment]
That's a really good point. Thank you for your help, and for creating Apollo. I'll go ahead and close the issue.
